version: "3.7"

services:
  web:
    build:
      dockerfile: Dockerfile
    command: gunicorn wsgi:application --bind 0.0.0.0:8000 --error-logfile ./error.log --access-logfile ./access.log --capture-output --log-level debug
    env_file:
      - ${ENV_FILE}
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/road/static
  nginx:
    build: ./nginx
    depends_on:
      - web
    volumes:
      - static_volume:/static
    ports:
      - "80:80"

volumes:
  static_volume: