name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Checking code with black
      run: black --diff --check $(git ls-files '*.py')
    - name: Checking code with pylint
      run: PYTHONPATH=$PYTHONPATH:$PWD pylint $(git ls-files '*.py')
    - name: Checking code with mypy
      run: mypy --strict $(git ls-files '*.py')
