name: Test ROAD backend

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Build database Docker image
        run: docker build -t postgres -f database-dockerfile .github

      - name: Run database Docker image
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: docker run -d -p 5432:5432 postgres

      - name: Build Docker image
        run: docker build -t road .

      - name: Run Docker container
        env:
          DJANGO_SETTINGS_MODULE: settings.test
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: localhost
        run: docker run road python manage.py test